before:
  hooks:
    - go mod download
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - arm64
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: protoc-extensions
      name: homebrew-tap
    name: protoc-gen-go-json
    description: A go-json plugin for protoc
    homepage: https://github.com/protoc-extensions/protoc-gen-go-json
